### ISSUE TITLE
Gofmt formats Go programs. It uses tabs for indentation and blanks for alignment. Alignment assumes that an editor is using a fixed-width font.

### ISSUE THREAD

**Issue by dominikbraun** [aligator/ControllerCase#1]
https://github.com/aligator/ControllerCase/blob/b9e09c54895169b6f94fc1a99728dd61541e9e32/model/case.go#L57-L69

[Gofmt formats Go programs. It uses tabs for indentation and blanks for alignment. Alignment assumes that an editor is using a fixed-width font. Without an explicit path, it processes the standard input. Given a file, it operates on that file; given a directory, it operates on all .go files in that directory, recursively. (Files starting with a period are ignored.) By default, gofmt prints the reformatted sources to standard output.](https://pkg.go.dev/cmd/gofmt)

**Comment by aligator** [comment]
^^ yes I experimented with [lunarvim](https://github.com/LunarVim/LunarVim) and was too lazy to check why it doesn't run the formatter....

Will do that today
